### ISSUE TITLE
JUCE as git submodule?

### ISSUE THREAD

**Issue by funkyfuture** [midibox/mios32#1]
I find it rather odd that a dependency library has to be placed in a user directory (`~/JUCE`)  and wonder whether JUCE could be included as git submodule.

**Comment by midibox** [comment]
I've to check this (with lower priority).

Originally I had sources under tools/juce, it wouldn't be a problem to provide this as a submodule again.

But it was problematic to generate valid Makefiles with Introjucer for all OS (many settings had to be changed to get relative paths to this directory, but maybe I just overlooked a certain switch)

Therefore I preferred to take the default setup, which is ~/JUCE under Linux and MacOS, and C:\JUCE under Windows.
