### ISSUE TITLE
expected ')' before '('

### ISSUE THREAD

**Issue by nervousapps** [midibox/mios32#3]
I try to compile the goom example and I have the following error : 

Creating object file for strtol.c
/Users/achillepenet/Documents/Projects/GOOM_STM32F4/mios32/programming_models/traditional/strtol.c:147:1: warning: parameter names (without types) in function declaration
 _strtol_r(rptr, nptr, endptr, base),
 ^~~~~~~~~
/Users/achillepenet/Documents/Projects/GOOM_STM32F4/mios32/programming_models/traditional/strtol.c:148:3: error: expected identifier or '(' before 'struct'
  (struct _reent *rptr _AND
   ^~~~~~
/Users/achillepenet/Documents/Projects/GOOM_STM32F4/mios32/programming_models/traditional/strtol.c:233:16: error: expected ')' before '(' token
 _DEFUN (strtol, (s, ptr, base),
                ^~
                )
make: *** [project_build//Users/achillepenet/Documents/Projects/GOOM_STM32F4/mios32/programming_models/traditional/strtol.o] Error 1

I'm on macOs, I can't find out what the issue is...

**Comment by sojastar** [comment]
Hi,

I have the same problem under both MacOS and Linux Ubuntu. What instructions did you follow to install the toolchain ?

**Comment by sojastar** [comment]
I installed the toolchain found here : http://www.midibox.org/mios32_toolchain/ ( as I should have from the beginning but I got wary when I saw it was last updated in 2013 ) and everything works fine now but for a few warnings.

Apparently the newer arm toolchain doesn't define the `_DEFUN`,  `_AND` and `_CONST` macros ( and a bunch of other ones too ) in _ansi.h.

**Comment by midibox** [comment]
goom compile is working again with latest arm-none-eabi-gcc (Arm GNU Toolchain 12.3.Rel1 (Build arm-12.35)) 12.3.1 20230626
